- platform: rest
  resource: http://127.0.0.1:8000/api/v1/switch
  name: mediacenter
  method: POST
  body_on: '{"active": true}'
  body_off: '{"active": false}'
  is_on_template: '{{value_json.status == True}}'
  timeout: 30
